AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create ALB, Target Group, and Security Group

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID where ALB and Target Group will be deployed

  SubnetA:
    Type: AWS::EC2::Subnet::Id
    Description: First Subnet ID for the ALB, must be in a unique Availability Zone

  SubnetB:
    Type: AWS::EC2::Subnet::Id
    Description: Second Subnet ID for the ALB, must be in a different Availability Zone than SubnetA

Resources:
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for the ALB
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VpcId
      Protocol: HTTP
      Port: 80
      TargetType: ip

  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: MyApplicationLoadBalancer
      Subnets:
        - !Ref SubnetA
        - !Ref SubnetB
      SecurityGroups:
        - !Ref ALBSecurityGroup
      Scheme: internet-facing
      Type: application


Outputs:
  ALBSecurityGroupId:
    Description: Security Group ID of the Application Load Balancer
    Value: !Ref ALBSecurityGroup

  ALBTargetGroupArn:
    Description: ARN of the Target Group for the ALB
    Value: !Ref ALBTargetGroup

  ApplicationLoadBalancerArn:
    Description: ARN of the Application Load Balancer
    Value: !Ref ApplicationLoadBalancer

  ApplicationLoadBalancerDNSName:
    Description: DNS Name of the Application Load Balancer
    Value: !GetAtt ApplicationLoadBalancer.DNSName
