AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Task Definitions for Frontend and Backend, including ECS Task Execution Role

Parameters:
  FrontendECRRepoURI:
    Type: String
    Description: The URI of the frontend ECR repository

  BackendECRRepoURI:
    Type: String
    Description: The URI of the backend ECR repository

Resources:
  ECSTaskExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: ECSTaskExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'

  FrontendTaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      Family: frontend
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: '256'
      Memory: '512'
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: frontend-container
          Image: !Ref FrontendECRRepoURI
          PortMappings:
            - ContainerPort: 80
          Essential: true

  BackendTaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      Family: backend
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: '256'
      Memory: '512'
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: backend-container
          Image: !Ref BackendECRRepoURI
          PortMappings:
            - ContainerPort: 3456
          Essential: true

Outputs:
  FrontendTaskDefinitionArn:
    Description: The ARN of the Frontend Task Definition
    Value: !Ref FrontendTaskDefinition

  BackendTaskDefinitionArn:
    Description: The ARN of the Backend Task Definition
    Value: !Ref BackendTaskDefinition

  ECSTaskExecutionRoleArn:
    Description: The ARN of the ECS Task Execution Role
    Value: !GetAtt ECSTaskExecutionRole.Arn
